/**
 * AIM — Shared Types
 * Core type definitions used across all AIM modules.
 */

import type { Message } from "@mariozechner/pi-ai";

// ============================================================================
// Worker / Process Management
// ============================================================================

/** Worker process state */
export type WorkerState = "starting" | "running" | "idle" | "dead";

/** Configuration for spawning a worker process */
export interface WorkerConfig {
  /** Unique worker ID (generated by WorkerPool) */
  workerId: string;
  /** Human-readable name (e.g. "scout", "worker-1") */
  name: string;
  /** The prompt/task to execute */
  prompt: string;
  /** Agent definition name to use (maps to ~/.pi/agent/agents/{name}.md) */
  agent?: string;
  /** Model override for this worker */
  model?: string;
  /** Allowed tools (comma-separated, passed to --tools) */
  tools?: string[];
  /** Working directory for the worker process */
  cwd?: string;
  /** If true, fire-and-forget (don't block caller) */
  background?: boolean;
  /** Path to parent session JSONL (for fork mode — inherit context) */
  forkFrom?: string;
  /** System prompt override (appended to worker's system prompt) */
  systemPrompt?: string;
  /** If true, use RPC mode (long-lived). If false/undefined, use print mode (one-shot) */
  rpcMode?: boolean;
  /** Agent ID for transcript persistence and resume */
  agentId?: string;
}

/** Runtime state of a managed worker */
export interface WorkerInfo {
  config: WorkerConfig;
  state: WorkerState;
  pid?: number;
  startedAt: number;
  /** Accumulated messages from the worker */
  messages: Message[];
  /** Accumulated stderr */
  stderr: string;
  /** Exit code (undefined while running) */
  exitCode?: number;
  /** Resolved when worker finishes (for sync mode) */
  donePromise?: Promise<void>;
  /** Resolve function for donePromise */
  doneResolve?: () => void;
  /** Reject function for donePromise */
  doneReject?: (err: Error) => void;
  /** ChildProcess reference (for RPC mode stdin/stdout communication) */
  process?: import("node:child_process").ChildProcess;
  /** RPC send helper (writes JSON line to stdin) */
  rpcSend?: (json: string) => void;
}

// ============================================================================
// Agent Definitions
// ============================================================================

/** Scope for agent discovery */
export type AgentScope = "user" | "project" | "both";

/** Parsed agent definition from markdown frontmatter */
export interface AgentConfig {
  name: string;
  description: string;
  tools?: string[];
  model?: string;
  systemPrompt: string;
  source: "user" | "project";
  filePath: string;
}

/** Result of agent discovery */
export interface AgentDiscoveryResult {
  agents: AgentConfig[];
  projectAgentsDir: string | null;
}

// ============================================================================
// Mailbox / Inter-Agent Communication
// ============================================================================

/** A message in an agent's inbox */
export interface TeammateMessage {
  from: string;
  text: string;
  timestamp: string;
  read: boolean;
  color?: string;
  summary?: string;
}

/** Structured message types for swarm protocol */
export type StructuredMessage =
  | { type: "shutdown_request"; request_id: string; from: string; reason?: string }
  | { type: "shutdown_response"; request_id: string; from: string; approved: boolean; reason?: string }
  | { type: "plan_approval_request"; request_id: string; from: string; plan: string }
  | { type: "plan_approval_response"; request_id: string; from: string; approved: boolean; feedback?: string };

// ============================================================================
// Team Management
// ============================================================================

/** Team member entry */
export interface TeamMember {
  agentId: string;
  name: string;
  agentType?: string;
  model?: string;
  color?: string;
  joinedAt: number;
  cwd: string;
}

/** Team file structure */
export interface TeamFile {
  name: string;
  description?: string;
  createdAt: number;
  leadAgentId: string;
  members: TeamMember[];
}

/** Configuration for spawning a teammate */
export interface SpawnTeammateConfig {
  name: string;
  prompt: string;
  team_name?: string;
  agent_type?: string;
  model?: string;
  plan_mode_required?: boolean;
  color?: string;
  description?: string;
  cwd?: string;
}

// ============================================================================
// Tasks
// ============================================================================

/** Task status */
export type TaskStatus = "pending" | "in_progress" | "completed" | "blocked" | "failed";

/** A single task in the shared task list */
export interface TaskItem {
  id: string;
  subject: string;
  description: string;
  status: TaskStatus;
  owner?: string;
  blockedBy: string[];
  createdAt: number;
  updatedAt: number;
}

// ============================================================================
// Cron
// ============================================================================

/** A scheduled cron job */
export interface CronJob {
  id: string;
  cron: string;
  prompt: string;
  recurring: boolean;
  durable: boolean;      // if true, persists to disk
  createdAt: number;
  nextRunAt: number;
  agentId?: string;       // optional, for teammate-scoped jobs
}

// ============================================================================
// Shared State (File System Paths)
// ============================================================================

/** Base directory for all AIM persistent state */
import * as nodePath from "node:path";

export function getAimDir(cwd: string): string {
  return nodePath.join(cwd, ".pi", "aim");
}

/** Team files directory */
export function getTeamsDir(cwd: string): string {
  return nodePath.join(getAimDir(cwd), "teams");
}

/** Inbox directory for a specific team */
export function getInboxesDir(cwd: string, teamName: string): string {
  return nodePath.join(getTeamsDir(cwd), teamName, "inboxes");
}

/** Task list directory for a specific team */
export function getTasksDir(cwd: string, teamName: string): string {
  return nodePath.join(getAimDir(cwd), "tasks", teamName);
}

/** Scheduled tasks file path */
export function getCronFilePath(cwd: string): string {
  return nodePath.join(getAimDir(cwd), "scheduled_tasks.json");
}

/** Agent transcript directory */
export function getAgentTranscriptDir(cwd: string): string {
  return nodePath.join(getAimDir(cwd), "agents");
}

/** Agent transcript file path for a specific agent ID */
export function getAgentTranscriptPath(cwd: string, agentId: string): string {
  return nodePath.join(getAgentTranscriptDir(cwd), `${agentId}.jsonl`);
}

/** Agent metadata file path */
export function getAgentMetadataPath(cwd: string, agentId: string): string {
  return nodePath.join(getAgentTranscriptDir(cwd), `${agentId}.meta.json`);
}

// ============================================================================
// Subagent Transcript (sidechain persistence)
// ============================================================================

/** Custom entry type for AIM subagent spawn records */
export const AIM_SUBAGENT_SPAWN_TYPE = "aim-subagent-spawn";

/** Custom entry type for AIM subagent result records */
export const AIM_SUBAGENT_RESULT_TYPE = "aim-subagent-result";

/** Data stored in a subagent spawn custom entry */
export interface SubagentSpawnData {
  agentId: string;
  agent: string;
  task: string;
  model?: string;
  tools?: string[];
  background: boolean;
  forkMode: boolean;
  transcriptFile: string;
}

/** Data stored in a subagent result custom entry */
export interface SubagentResultData {
  agentId: string;
  status: "completed" | "failed" | "aborted";
  summary: string;
  usage: {
    input: number;
    output: number;
    cacheRead: number;
    cacheWrite: number;
    turns: number;
  };
  exitCode: number;
  model?: string;
}