/**
 * AIM — Shared Types
 * Core type definitions used across all AIM modules.
 */

import type { Message } from "@earendil-works/pi-ai";

// ============================================================================
// Worker / Process Management
// ============================================================================

/** Worker process state */
export type WorkerState = "starting" | "running" | "idle" | "dead";

/** Configuration for spawning a worker process */
export interface WorkerConfig {
  /** Unique worker ID (generated by WorkerPool) */
  workerId: string;
  /** Human-readable name (e.g. "scout", "worker-1") */
  name: string;
  /** The prompt/task to execute */
  prompt: string;
  /** Agent definition name to use (maps to ~/.pi/agent/agents/{name}.md) */
  agent?: string;
  /** Model override for this worker */
  model?: string;
  /** Allowed tools (comma-separated, passed to --tools) */
  tools?: string[];
  /** Working directory for the worker process */
  cwd?: string;
  /** If true, fire-and-forget (don't block caller) */
  background?: boolean;
  /** Path to parent session JSONL (for fork mode — inherit context) */
  forkFrom?: string;
  /** System prompt override (appended to worker's system prompt) */
  systemPrompt?: string;
  /** If true, use RPC mode (long-lived). If false/undefined, use print mode (one-shot) */
  rpcMode?: boolean;
  /** Agent ID for transcript persistence and resume */
  agentId?: string;
  /** Team name this worker belongs to (passed to the child process via the
   *  TEAMMATE_TEAM env var so teammates can locate their mailbox).
   *  Typed field — previously threaded via an unsafe `(config as Record).team_name` cast. */
  team_name?: string;
}

/** Runtime state of a managed worker */
export interface WorkerInfo {
  config: WorkerConfig;
  state: WorkerState;
  pid?: number;
  startedAt: number;
  /** Accumulated messages from the worker */
  messages: Message[];
  /** Accumulated stderr */
  stderr: string;
  /** Exit code (undefined while running) */
  exitCode?: number;
  /** Resolved when worker finishes (for sync mode) */
  donePromise?: Promise<void>;
  /** Resolve function for donePromise */
  doneResolve?: () => void;
  /** Reject function for donePromise */
  doneReject?: (err: Error) => void;
  /** ChildProcess reference (for RPC mode stdin/stdout communication) */
  process?: import("node:child_process").ChildProcess;
  /** RPC send helper (writes JSON line to stdin) */
  rpcSend?: (json: string) => void;
  /** Number of agent_end events received */
  turnCount?: number;
  /** True once kill() has been called and SIGTERM sent (idempotency guard —
   *  prevents double-kill and lets the SIGKILL escalation timer distinguish
   *  "killed by us, awaiting exit" from a genuinely dead worker). */
  killing?: boolean;
}

// ============================================================================
// Agent Definitions
// ============================================================================

/** Scope for agent discovery */
export type AgentScope = "user" | "project" | "both";

/** Parsed agent definition from markdown frontmatter */
export interface AgentConfig {
  name: string;
  description: string;
  tools?: string[];
  model?: string;
  systemPrompt: string;
  source: "user" | "project";
  filePath: string;
}

/** Result of agent discovery */
export interface AgentDiscoveryResult {
  agents: AgentConfig[];
  projectAgentsDir: string | null;
}

// ============================================================================
// Mailbox / Inter-Agent Communication
// ============================================================================

/** A message in an agent's inbox */
export interface TeammateMessage {
  from: string;
  text: string;
  timestamp: string;
  read: boolean;
  color?: string;
  summary?: string;
}

/** Structured message types for swarm protocol */
export type StructuredMessage =
  | { type: "shutdown_request"; request_id: string; from: string; reason?: string }
  | { type: "shutdown_response"; request_id: string; from: string; approved: boolean; reason?: string }
  | { type: "plan_approval_request"; request_id: string; from: string; plan: string }
  | { type: "plan_approval_response"; request_id: string; from: string; approved: boolean; feedback?: string };

// ============================================================================
// Team Management
// ============================================================================

/** Team member entry */
export interface TeamMember {
  agentId: string;
  name: string;
  agentType?: string;
  model?: string;
  color?: string;
  joinedAt: number;
  cwd: string;
}

/** Team file structure */
export interface TeamFile {
  name: string;
  description?: string;
  createdAt: number;
  leadAgentId: string;
  members: TeamMember[];
}

/** Configuration for spawning a teammate */
export interface SpawnTeammateConfig {
  name: string;
  prompt: string;
  team_name?: string;
  agent_type?: string;
  model?: string;
  plan_mode_required?: boolean;
  color?: string;
  description?: string;
  cwd?: string;
}

// ============================================================================
// Tasks
// ============================================================================

/** Task type — determines execution strategy and UI presentation */
export type TaskType =
  | "local_agent"          // Sub-agent spawned via worker-pool
  | "in_process_teammate"  // In-process teammate (future)
  | "local_bash"           // Shell command task
  | "local_workflow"       // Chain/workflow task
  | "monitor"              // Monitor/observation task
  | "dream";               // Memory consolidation task (aim-services)

/** Task status — full 5-state lifecycle */
export type TaskStatus = "pending" | "in_progress" | "completed" | "failed" | "killed";

/** Valid state transitions map
 *
 *  pending → failed:  pre-condition not met after creation (e.g. blocker also failed)
 *  pending → killed:  proactively cancelled before starting
 *  pending → in_progress:  claimed by an agent and work begins
 */
export const VALID_TRANSITIONS: Record<TaskStatus, TaskStatus[]> = {
  pending:     ["in_progress", "failed", "killed"],
  in_progress: ["completed", "failed", "killed"],
  completed:   [],  // terminal
  failed:      [],  // terminal
  killed:      [],  // terminal
};

/** Check if a status is terminal (no further transitions allowed) */
export function isTerminalStatus(status: TaskStatus): boolean {
  return status === "completed" || status === "failed" || status === "killed";
}

/** Check if a transition from -> to is valid */
export function canTransition(from: TaskStatus, to: TaskStatus): boolean {
  return VALID_TRANSITIONS[from]?.includes(to) ?? false;
}

/** A single task in the shared task list */
export interface TaskItem {
  id: string;
  /** Task type — determines execution strategy */
  type: TaskType;
  subject: string;
  description: string;
  /** Present-tense display text (e.g. "Running tests") */
  activeForm?: string;
  status: TaskStatus;
  /** Agent that owns this task. undefined = unowned/never assigned.
   *  IMPORTANT: always check with != null (matches both null from legacy JSON
   *  and undefined from current code). Never use !== undefined alone, as
   *  deserialized legacy data may have owner: null. */
  owner?: string;
  /** IDs of tasks this task blocks (this → them) */
  blocks: string[];
  /** IDs of tasks that block this task (them → this) */
  blockedBy: string[];
  /** Timestamp of last reference cleanup (from deleteTask). Separate from
   *  updatedAt to avoid affecting stale/orphan detection that relies on updatedAt. */
  refsCleanedAt?: number;
  /** Arbitrary metadata for extensibility */
  metadata?: Record<string, unknown>;
  createdAt: number;
  updatedAt: number;
}

// ============================================================================
// Cron
// ============================================================================

/** A scheduled cron job */
export interface CronJob {
  id: string;
  cron: string;
  prompt: string;
  recurring: boolean;
  durable: boolean;      // if true, persists to disk
  createdAt: number;
  nextRunAt: number;
  agentId?: string;       // optional, for teammate-scoped jobs
}

// ============================================================================
// Shared State (File System Paths)
// ============================================================================

/** Base directory for all AIM persistent state */
import * as nodePath from "node:path";

export function getAimDir(cwd: string): string {
  return nodePath.join(cwd, ".pi", "aim");
}

/** Validate a path segment (team name, task id, agent id, recipient name).
 *
 * These identifiers are interpolated directly into filesystem paths (e.g.
 * `task-${taskId}.json`, `teams/${teamName}/inboxes/`). A value containing
 * `..` or `/` would escape its intended directory (path traversal) and a
 * value with other special chars could clobber arbitrary files.
 *
 * Allowed: ASCII letters, digits, hyphen, underscore (no path separators,
 * dots, or shell metacharacters). Throws on invalid input so callers surface
 * the problem immediately rather than silently writing outside the AIM dir.
 *
 * Task IDs are numeric strings assigned by createTask(), so they always
 * pass; this guards against LLM-supplied `task_id` / `team_name` / `agent`
 * values that could otherwise traverse. */
const VALID_ID_RE = /^[a-zA-Z0-9_-]+$/;
export function sanitizeId(id: string, kind: string): string {
  if (typeof id !== "string" || id.length === 0 || !VALID_ID_RE.test(id)) {
    throw new Error(`Invalid ${kind}: ${JSON.stringify(id)} (must match [a-zA-Z0-9_-]+)`);
  }
  return id;
}

/** Team files directory */
export function getTeamsDir(cwd: string): string {
  return nodePath.join(getAimDir(cwd), "teams");
}

/** Inbox directory for a specific team */
export function getInboxesDir(cwd: string, teamName: string): string {
  return nodePath.join(getTeamsDir(cwd), sanitizeId(teamName, "team name"), "inboxes");
}

/** Task list directory for a specific team */
export function getTasksDir(cwd: string, teamName: string): string {
  return nodePath.join(getAimDir(cwd), "tasks", sanitizeId(teamName, "team name"));
}

/** Scheduled tasks file path */
export function getCronFilePath(cwd: string): string {
  return nodePath.join(getAimDir(cwd), "scheduled_tasks.json");
}

/** Agent transcript directory */
export function getAgentTranscriptDir(cwd: string): string {
  return nodePath.join(getAimDir(cwd), "agents");
}

/** Agent transcript file path for a specific agent ID */
export function getAgentTranscriptPath(cwd: string, agentId: string): string {
  return nodePath.join(getAgentTranscriptDir(cwd), `${sanitizeId(agentId, "agent id")}.jsonl`);
}

/** Agent metadata file path */
export function getAgentMetadataPath(cwd: string, agentId: string): string {
  return nodePath.join(getAgentTranscriptDir(cwd), `${sanitizeId(agentId, "agent id")}.meta.json`);
}

// ============================================================================
// Subagent Transcript (sidechain persistence)
// ============================================================================

/** Custom entry type for AIM subagent spawn records */
export const AIM_SUBAGENT_SPAWN_TYPE = "aim-subagent-spawn";

/** Custom entry type for AIM subagent result records */
export const AIM_SUBAGENT_RESULT_TYPE = "aim-subagent-result";

/** Data stored in a subagent spawn custom entry */
export interface SubagentSpawnData {
  agentId: string;
  agent: string;
  task: string;
  model?: string;
  tools?: string[];
  background: boolean;
  forkMode: boolean;
  transcriptFile: string;
}

/** Data stored in a subagent result custom entry */
export interface SubagentResultData {
  agentId: string;
  status: "completed" | "failed" | "aborted";
  summary: string;
  usage: {
    input: number;
    output: number;
    cacheRead: number;
    cacheWrite: number;
    turns: number;
  };
  exitCode: number;
  model?: string;
}